### ISSUE TITLE
How to use this module as URL import?

### ISSUE THREAD

**Issue by despin** [brianboyko/denodash#4]

**Comment by crazy4groovy** [comment]
Same question here.

**Comment by chovy** [comment]
same. can't figure it out. lol

**Comment by chovy** [comment]
I figure out you can import one function like this:

`import sample from 'https://deno.land/x/denodash@v0.1.3/src/collection/sample.ts'`

i don't know about the whole lib though

**Comment by kerryboyko** [comment]
In the documentation directory of the source code you should be able to see where everything is... it's to my personal shame that I'm able to generate these MD files but can't be bothered to figure out how to use them to get automatically generated gh-pages up and running for each.  :(   I could use some help with contributions.  Anyone know Jekyll and is up to the challenge? 

In the meantime, all the files can be found at https://deno.land/x/denodash/@v0.1.3/src/--- and the name of the file, like any other deno third party library.
