### ISSUE TITLE
sortBy doesn't appear to work on strings

### ISSUE THREAD

**Issue by chovy** [brianboyko/denodash#6]
trying to sort an array of objects and it errors out because `d.domain` is not a number.

```
sortBy(arr, ['domain'])
```

**Comment by kerryboyko** [comment]
Howdy.  

I've added a new method (and updated to 0.1.3) based on your use case; while `sortBy(arr, ['domain'])` will still throw an error, try either one of these two solutions:

The brand NEW!

`sortByProperty(arr, 'domain')`

Or the slighly less glamourous

`sortBy(arr, (a, b) => a.domain.localeCompare(b.domain))`
